version: '3.4'
services:
  postgres:
     image: postgres:latest
     ports:
       - 5000:5432
     volumes:
       - ./src/main/proyectoescalada-postgres-1/table-creation/tablas.sql:/docker-entrypoint-initdb.d/tablas.sql
     environment:
      BBDD_HOST_WRITER: postgres
      POSTGRES_PASSWORD: postgres
      BBDD_NAME: postgres
