version: '3.4'
services:
  postgres:
  
     image: postgres:latest
     ports:
       - 5000:5432
       
     volumes:
     
     ##Schema
       - ./src/main/proyectoescalada-postgres-1/schema-creation/core.sql:/docker-entrypoint-initdb.d/core.sql
     ##Datos 
       - ./src/main/proyectoescalada-postgres-1/table-creation/tablas.sql:/docker-entrypoint-initdb.d/tablas.sql

     environment:
     
      BBDD_HOST_WRITER: postgres
      POSTGRES_PASSWORD: postgres
      BBDD_NAME: postgres
