package com.climbtogether.app.entity;
//Generated 28-may-2020 20:41:23 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
* ReservaId generated by hbm2java
*/
@Embeddable
public class ReservaId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5833128228324872425L;
	private int idreserva;
	private int idPasajero;
	private int idviaje;

	public ReservaId() {
	}

	public ReservaId(int idreserva, int idPasajero, int idviaje) {
		this.idreserva = idreserva;
		this.idPasajero = idPasajero;
		this.idviaje = idviaje;
	}

	@Column(name = "idreserva", nullable = false)
	public int getIdreserva() {
		return this.idreserva;
	}

	public void setIdreserva(int idreserva) {
		this.idreserva = idreserva;
	}

	@Column(name = "idPasajero", nullable = false)
	public int getIdPasajero() {
		return this.idPasajero;
	}

	public void setIdPasajero(int idPasajero) {
		this.idPasajero = idPasajero;
	}

	@Column(name = "idviaje", nullable = false)
	public int getIdviaje() {
		return this.idviaje;
	}

	public void setIdviaje(int idviaje) {
		this.idviaje = idviaje;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReservaId))
			return false;
		ReservaId castOther = (ReservaId) other;

		return (this.getIdreserva() == castOther.getIdreserva())
				&& (this.getIdPasajero() == castOther.getIdPasajero())
				&& (this.getIdviaje() == castOther.getIdviaje());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdreserva();
		result = 37 * result + this.getIdPasajero();
		result = 37 * result + this.getIdviaje();
		return result;
	}

}
