package com.climbtogether.app.entity;

import java.sql.Timestamp;

// Generated 28-may-2020 20:41:23 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonFormat;


/**
 * Viaje generated by hbm2java
 */
@Entity
@Table(name = "viajes")
public class Viaje implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2527933666793982900L;
	private Integer id;
	private Usuario conductor;
	private String lugar;
	private String tipo;
	private int numplazasdisponibles;
	private String fecha_salida_string;
	private Timestamp fechasalida;
	private Provincia provincia;
	
	private Set<Reserva> reservas = new HashSet<Reserva>(0);

	public Viaje() {
	}

	public Viaje(Usuario conductor, String lugar, int numplazasdisponibles, String fecha_salida_string, Timestamp fechasalida, Provincia provincia) {
		this.conductor = conductor;
		this.lugar = lugar;
		this.numplazasdisponibles = numplazasdisponibles;
		this.fecha_salida_string = fecha_salida_string;
		this.fechasalida = fechasalida;
		this.provincia = provincia;
	}

	public Viaje(Usuario conductor, String lugar, String tipo, int numplazasdisponibles, String fecha_salida_string, Timestamp fechasalida, Set<Reserva> reservas, Provincia provincia) {
		this.conductor = conductor;
		this.lugar = lugar;
		this.numplazasdisponibles = numplazasdisponibles;
		this.fecha_salida_string = fecha_salida_string;
		this.fechasalida = fechasalida;
		this.reservas = reservas;
		this.provincia = provincia;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idviaje", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idConductor", nullable = false)
	public Usuario getConductor() {
		return this.conductor;
	}

	public void setConductor(Usuario conductor) {
		this.conductor = conductor;
	}

	@Column(name = "lugar", nullable = false, length = 30)
	public String getLugar() {
		return this.lugar;
	}
	
	public void setLugar(String lugar) {
		this.lugar = lugar;
	}
	
	@Column(name = "tipo", nullable = false, length = 30)
	public String getTipo() {
		return tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "numplazasdisponibles", nullable = false)
	public int getNumplazasdisponibles() {
		return this.numplazasdisponibles;
	}

	public void setNumplazasdisponibles(int numplazasdisponibles) {
		this.numplazasdisponibles = numplazasdisponibles;
	}

	@JsonFormat(pattern="yyyy-MM-dd")
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechasalida", length = 19)
	public Date getFechasalida() {
		return this.fechasalida;
	}

	public void setFechasalida(Timestamp fechasalida) {
		this.fechasalida = fechasalida;
	}

	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "viaje")
	public Set<Reserva> getReservas() {
		return this.reservas;
	}

	public void setReservas(Set<Reserva> reservas) {
		this.reservas = reservas;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	public Provincia getProvincia() {
		return provincia;
	}

	public void setProvincia(Provincia provincia) {
		this.provincia = provincia;
	}

	@Column(name = "fecha_salida_string")
	public String getFechasalidaString() {
		return fecha_salida_string;
	}

	public void setFechasalidaString(String fecha_salida_string) {
		this.fecha_salida_string = fecha_salida_string;
	}
	
	
	
}