name: Deployment Pipeline
on:
    push:
        branches:
        - main
jobs:
    deploy:
        runs-on: ubuntu-18.04
        steps:
        -   uses: actions/checkout@v3
            with:
                fetch-depth: 0
        -   uses: actions/setup-java@v3
            with:
                java-version: '11'
                distribution: adopt
        -   name: Install dependencies
            run: mvn clean install
        -   name: Deploy to heroku
        -   uses: akhileshns/heroku-deploy@v3.12.12
            with:
                heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                heroku_app_name: ${{secrets.HEROKU_APP}}
                heroku_email: ${{secrets.HEROKU_API_EMAIL}}
                
                
                
                
                
                
                
                
                