name: Deployment Pipeline

on:
    push:
        branches:
        - main

jobs:
    deploy:
        runs-on: ubuntu-18.04
        steps:
        -   uses: actions/checkout@v3
            with:
                fetch-depth: 0
        -   uses: actions/setup-java@v3
            with:
                java-version: '11'
                distribution: 'adopt'      
        -   services:
                postgres:
                    image: postgres:latest
                    env:
                        BBDD_HOST_WRITER: postgres
                        POSTGRES_PASSWORD: postgres
                        BBDD_NAME: postgres

                    ports:
                        - "5000:5432"
        -   name: Install dependencies
            run: mvn clean install
          